### ISSUE TITLE
hints for WSLg?

### ISSUE THREAD

**Issue by andymule** [fwcd/swift-graphics#4]
I have a dream of this running on Windows via WSL2, specifically WSLg

Most other graphics examples are "just working" for me, but this one doesn't do anything. Any ideas?

**Comment by fwcd** [comment]
Hi, that's an interesting idea, this library doesn't include a GUI layer though, since it's mostly just a Swift layer above Cairo and primary intended for rendering to image buffers/files. However, if you'd like to dig into this, feel free.
